// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsklfRtLYqXO4XSQYdXCIFe2fdnWpzjbY',
    appId: '1:487493879495:web:d54703a2afa97c271ca0e2',
    messagingSenderId: '487493879495',
    projectId: 'code4fun-40c9c',
    authDomain: 'code4fun-40c9c.firebaseapp.com',
    storageBucket: 'code4fun-40c9c.firebasestorage.app',
    measurementId: 'G-E7MH865HND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLfB9NFRr4Q4p2WTAzpZdIURSabwyGsOc',
    appId: '1:487493879495:android:ccf691e98d6a8cfd1ca0e2',
    messagingSenderId: '487493879495',
    projectId: 'code4fun-40c9c',
    storageBucket: 'code4fun-40c9c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZj49wCVkj1u2Na4JZCAtgmrf7U0kUMjk',
    appId: '1:487493879495:ios:1cd3f74ee02629b21ca0e2',
    messagingSenderId: '487493879495',
    projectId: 'code4fun-40c9c',
    storageBucket: 'code4fun-40c9c.firebasestorage.app',
    iosBundleId: 'com.example.code4fun',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZj49wCVkj1u2Na4JZCAtgmrf7U0kUMjk',
    appId: '1:487493879495:ios:1cd3f74ee02629b21ca0e2',
    messagingSenderId: '487493879495',
    projectId: 'code4fun-40c9c',
    storageBucket: 'code4fun-40c9c.firebasestorage.app',
    iosBundleId: 'com.example.code4fun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsklfRtLYqXO4XSQYdXCIFe2fdnWpzjbY',
    appId: '1:487493879495:web:2a0c2ddd275706901ca0e2',
    messagingSenderId: '487493879495',
    projectId: 'code4fun-40c9c',
    authDomain: 'code4fun-40c9c.firebaseapp.com',
    storageBucket: 'code4fun-40c9c.firebasestorage.app',
    measurementId: 'G-GTP996HW8G',
  );

}